INSERT INTO user_roles (id, role_name) VALUES (0, 'ANONYMOUS');
INSERT INTO user_roles (id, role_name) VALUES (1, 'USER');
INSERT INTO user_roles (id, role_name) VALUES (2, 'ADMIN');

INSERT INTO USERS (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, ROLE_ID)
VALUES (0, 'test@example.com', 'test', 'test', 'test', 1);

INSERT INTO USERS (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, ROLE_ID)
VALUES (1, 'test@example.com', 'test2', 'test2', 'test2', 1);

INSERT INTO QUIZZES (ID, TITLE, CONTENT, EXPIRATION_TIME, ANONYMOUS, STATUS, AUTHOR_ID)
VALUES (0, 'test_quiz_1', 'test_quiz_content_1', CURRENT_TIMESTAMP, 0, 1, 0);

INSERT INTO QUIZZES (ID, TITLE, CONTENT, EXPIRATION_TIME, ANONYMOUS, STATUS, AUTHOR_ID)
VALUES (1, 'test_quiz_2', 'test_quiz_content_2', CURRENT_TIMESTAMP, 1, 1, 0);

INSERT INTO ANSWERS (ID, TITLE, TYPE, ANSWER_ORDER, QUIZ_ID)
VALUES (0, 'test_answer_1', 'one', 0, 0);

INSERT INTO ANSWERS (ID, TITLE, TYPE, ANSWER_ORDER, QUIZ_ID)
VALUES (1, 'test_answer_2', 'one', 0, 0);

INSERT INTO HISTORY (ID, ANSWER_ID, USER_ID, ANSWER_TIME, QUIZ_ID)
VALUES (0, 0, 0, CURRENT_TIMESTAMP, 0);